# name,age = input('Enter your name & agr:').split(',')
# print('Your name in reverse is {} and age is {}'.format(name[::-1],age[::-1]))
print('-------Exercise-3')
name, Cha = input('Enter comma seperated name and character: ').split(',')
print('Length of your name is {} and character count is {}.'.format(len(name),name.lower().count(Cha.lower())))
